# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Qubinode Docs"
email: tcij1013@gmail.com
description: "Qubinode documentation hub."
baseurl: "/jekyll-help-center-theme"
url: "http://quinalha.me"
twitter_username: ""
github_username:  ""
color_theme:  "#0081ff"
color_text:  "#fff"
language:  "en"

# Build settings
markdown: kramdown
permalink: /:title/
gems: [jekyll-paginate]
paginate: 5

# Plugins
plugins_dir:
  - jekyll-admin
